"App Code":
- changed-files:
  - any-glob-to-any-file:
    - app/**
    - '*.py'
    - requirements.txt

"Github Config":
- changed-files:
  - any-glob-to-any-file: .github/**

"Computer Science":
- changed-files:
  - any-glob-to-any-file: Computer Science/**

"English Lanuage":
- changed-files:
  - any-glob-to-any-file: English Language/**

"French":
- changed-files:
  - any-glob-to-any-file: French/**

"Maths":
- changed-files:
  - any-glob-to-any-file: Maths/**
