"En ville" = "In town"
"la boîte de nuit" = "nightclub"
"le bowling" = "bowling alley"
"le café" = "café"
"le centre commercial" = "shopping centre"
"le cinéma" = "cinema"
"les magasins" = "shops"
"la patinoire" = "ice rink"
"la piscine" = "swimming pool"
"la plage" = "beach"
"le théâtre" = "theatre"
"dans" = "in"
"derrère" = "behind"
"devant" = "in front of"
"entre" = "between"
"en face de" = "opposite"
"à côté de" = "next to"
"près de" = "near"
