"L'amitié" = "Friendship"
"Un bon ami est..." = "A good friend is..."
"de bonne humeur" = "in a good mood"
"compréhensif" = "understanding"
"équilibré" = "balanced"
"honnête" = "honest"
"indépendant" = "independent"
"modeste" = "modest"
"patient" = "patient"
"sûr de lui" = "self-confident"
"Un bon ami n'est pas..." = "A good friend is not..."
"de mauvaise humeur" = "in a bad mood"
"déprimé" = "depressed"
"pessimiste" = "pessimistic"
"prétentieux" = "pretentious"
"vaniteux" = "conceited"
"Il/Elle ..." = "He/She ..."
"croit en moi" = "believes in me"
"dit toujours la vérité" = "always tells the truth"
"me fait rire" = "makes me laugh"
"prend soin de moi" = "takes care of me"
"voit le bon côté des choses" = "sees the bright side of things"
