"La famille" = "Family members"
"le beau-père" = "stepfather"
"la belle-mère" = "stepmother"
"le beau-frère" = "brother-in-law"
"la belle-sœur" = "sister-in-law"
"le demi-frère" = "half-brother"
"la demi-sœur" = "half-sister"
"la fille" = "daughter"
"le fils" = "son"
"l'enfant" = "child"
"le petit-enfant" = "grandchild"
"le mari" = "husband"
"la femme" = "wife"
"l'ex-mari" = "ex-husband"
"l'ex-femme" = "ex-wife"
