"Les traits de personnalité" = "Qualities"
"le sens de l'humour" = "sense of humour"
"la patience" = "patience"
"la générosité" = "generosity"
"la gentillesse" = "kindness"
"la fidélité" = "loyalty"
"la modestie" = "modesty"
"l'honnêtété" = "honesty"
"l'optimisme" = "optimism"
