"Les adjectifs de personnalité" = "Personality adjectives"
"Il/Elle est..." = "He/She is..."
"agaçant" = "annoying"
"aimable" = "likeable"
"amusant" = "amusing"
"arrogant" = "arrogant"
"bavard" = "talkative"
"charmant" = "charming"
"drôle" = "funny"
"égoïste" = "selfish"
"fidèle" = "loyal"
"fort" = "strong"
"généreux" = "generous"
"gentil" = "kind"
"impatient" = "impatient"
"jaloux" = "jealous"
"méchant" = "mean"
"paresseux" = "lazy"
"poli" = "polite"
"sage" = "well-behaved"
"sensible" = "sensitive"
"sérieux" = "serious"
"sympathique" = "nice"
"têtu" = "stubborn"
"travailleur" = "hard-working"
"triste" = "sad"
