"Les rapports en famille" = "Family relationships"
"se confier à" = "to confide in"
"se disputer avec" = "to argue with"
"s'entendre bien avec" = "to get on well with"
"se fâcher contre" = "to get angry with"
"s'intéresser à" = "to be interested in"
"s'occuper de" = "to look after"
"s'aimer" = "to love each other"
"se chamailler" = "to squabble"
"mort" = "dead"
"décédé" = "deceased"
"divorcé" = "divorced"
"séparé" = "separated"
