"Ma description physique" = "My physical description"
"J'ai les cheveux ..." = "I have ... hair"
"courts" = "short"
"longs" = "long"
"mi-longs" = "medium-length"
"raides" = "straight"
"bouclés" = "curly"
"frisés" = "frizzy"
"noirs" = "black"
"bruns" = "brown"
"châtains" = "chestnut"
"blonds" = "blond"
"roux" = "red"
"gris" = "grey"
"blancs" = "white"
"J'ai les yeux ..." = "I have ... eyes"
"bleus" = "blue"
"verts" = "green"
"marron" = "brown"
"J'ai ..." = "I have ..."
"des boutons" = "spots"
"une barbe" = "a beard"
"une moustache" = "a moustache"
"Je suis ..." = "I am ..."
"grand" = "tall"
"petit" = "short"
"de taille moyenne" = "of medium height"
"mince" = "slim"
"gros" = "fat"
"beau" = "handsome"
"belle" = "beautiful"
"joli" = "pretty"
"moche" = "ugly"
"Je porte des lunettes" = "I wear glasses"
