"On décrit une sortie" = "Describing a night out"
"hier soir" = "last night"
"à 20 heures" = "at 8pm"
"d'abord" = "first of all"
"après" = "after"
"puis" = "then"
"ensuite" = "next"
"visité le musée" = "visited the museum"
"vu un match" = "saw a match"
"vu un exposittion" = "saw an exhibition"
"mangé dans un restaurant" = "ate in a restaurant"
"refusé de manger" = "refused to eat"
"bu un coca" = "drank a cola"
"dit «au revoir»" = "said 'good-bye'"
"embrassé ..." = "kissed ..."
"allé à un pub" = "went to a pub"
"resté dehors sur la terrasse" = "stayed outside on the terrace"
"entré dans un restaurant" = "went into a restaurant"
"sorti" = "went out"
"parti" = "left"
"monté dans le bus" = "got on the bus"
"rentré à la maison" = "went home"
"tombé amoureux" = "fell in love"
