"On décrit un ami" = "Describing a friend"
"Il/Elle ..." = "He/She ..."
"mesure 1,68 mètre" = "is 1m 68cm tall"
"sebmle timide" = "seems shy"
"porte un appareil dentaire" = "wears braces"
"a l'air cool" = "looks cool"
"a des yeux qui inspirent confiance" = "has eyes which convey confidence"
"On a les mêmes centres d'intérêt" = "We have the same interests"
