"On de패crit sa famille" = "Describing family members"
"adorable" = "adorable"
"de패brouillard" = "resourceful"
"dynamique" = "dynamic"
"e패nergique" = "energetic"
"plein d'e패nergie" = "full of energy"
"extraverti" = "extroverted"
"fragile" = "fragile"
"instable" = "unstable"
"introverti" = "introverted"
