"On va sortir" = "Going out"
"Je vais ..." = "I am going ..."
"aller au match" = "to go to the match"
"faire les magasins" = "to go shopping"
"faire du patinage" = "to go ice-skating"
"manger au fast-food" = "to eat in a fast-food restaurant"
"aller au cinéma" = "to go to the cinema"
"faire du skate" = "to go skateboarding"
"voir un spectacle" = "to see a show"
"jouer à des jeux vidéo" = "to play video games"
"venir chez moi" = "to come to my place"
"Tu veux venir?" = "Do you want to come?"
"Tu peux venir?" = "Can you come?"
"On se retrouve quand?" = "When shall we meet?"
"On se retrouve où?" = "Where shall we meet?"
"On se retrouve à quelle heure?" = "At what time shall we meet?"
"Tu y vas avec qui?" = "Who are you going there with?"
"Tu y vas comment?" = "How are you getting there?"
"D'accord" = "OK"
"À plus tard!" = "See you later!"
