"Parler de son enfance" = "Talking about your childhood"
"Quand j'étais plus jeune, ..." = "When I was younger, ..."
"j'habitais avec (mon papa et ma maman)" = "I lived with (my mum and dad)"
"j'allais à l'école primaire" = "I went to primary school"
"j'avais (les cheveux blonds)" = "I had (blond hair)"
"j'étais (mignon)" = "I was (cute)"
"je jouais (à «cache-cache»)" = "I played ('hide and seek')"
"j'aimais (les bonbons)" = "I liked (sweets)"
"je détestais (les épinards)" = "I hated (spinach)"
"je portais (un maillot du PSG)" = "I wore (a PSG shirt)"
"je rêvais d'être ..." = "my dream was to be ..."
