"Qui est-ce que tu admires?" = "Who do you admire?"
"Mon modèle s'appelle..." = "My role model is called..."
"Moi, j'admire ..." = "Personally, I admire..."
"Mon héros, c'est ..." = "My hero is..."
"Ma héroïne, c'est ..." = "My heroine is..."
"J'aimerais bien ̂etre comment lui/elle" = "I would like to be like him/her"
"J'admire sa créativité" = "I admire his/her creativity"
"m'impressione énormément" = "impresses me a lot"
"a travaillé très dur pour devenir ..." = "worked very hard to become..."
"est devenu" = "became"
"aide" = "helps"
"a aidé" = "helped"
"a du courage" = "has courage"
"avait de la détermination" = "had determination"
"est courageux face à des dangers terribles" = "is brave in the face of terrible dangers"
"était courageuse" = "was brave"
"lutte pour ..." = "fights for..."
"a lutté pour ..." = "fought for..."
"a obtenu" = "achieved"
"a sauvé la vie de ..." = "saved the life of..."
"C'est un enfant adopté, comme moi" = "He/She is adopted, like me"
