exam_board = "Edexcel IGCSE"
subject = "English Language A"
code = "4EA1"

[[papers]]
name = "Non-fiction Texts and Transactional Writing"
number = 1
code = "4EA1/01"
topics = [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 1.10, 2]

[[topics]]
title = "The Danger of a Single Story"
number = 1.1

title = "A Passage to Africa"
number = 1.2

[[topics]]
title = "The Explorer's Daughter"
number = 1.3

[[topics]]
title = "Explorers, or boys messing about? Either way, taxpayer gets rescue bill"
number = 1.4

[[topics]]
title = "127 hours: Between a Rock and a Hard Place"
number = 1.5

[[topics]]
title = "Young and dyslexic? You've got it going on"
number = 1.6

[[topics]]
title = "A game of Polo with a Headless Goat"
number = 1.7

[[topics]]
title = "Beyond the Sky and Earth: A Journey into Bhutan"
number = 1.8

[[topics]]
title = "H is for Hawk"
number = 1.9

[[topics]]
title = "Chinese Cinderella"
number = 1.10

[[topics]]
title = "Transactional Writing"
number = 2
