name: Compile Notes

on:
  pull_request:
    branches: [ "main" ]
    types: [ opened, synchronize, reopened, ready_for_review, review_requested ]

permissions:
  contents: read

jobs:
  fail_if_request_is_draft:
    if: github.event.pull_request.draft == true
    runs-on: ubuntu-latest
    steps:
    - name: Fail if PR is draft
      run: exit 1

  compile_notes:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Setup Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - name: Compile Computer Science Notes
      if: contains(github.event.pull_request.labels.*.name, 'Computer Science') || contains(github.event.pull_request.labels.*.name, 'App Code')
      run: |
        python main.py compile topic "Computer Science"
        git add .
        git commit -m "Compile Computer Science Notes" || exit 0
    - name: Compile English Language Notes
      if: contains(github.event.pull_request.labels.*.name, 'English Language') || contains(github.event.pull_request.labels.*.name, 'App Code')
      run: |
        python main.py compile topic "English Language"
        git add .
        git commit -m "Compile English Language Notes" || exit 0
    - name: Compile Maths Notes
      if: contains(github.event.pull_request.labels.*.name, 'Maths') || contains(github.event.pull_request.labels.*.name, 'App Code')
      run: |
        python main.py compile topic "Maths"
        git add .
        git commit -m "Compile Maths Notes" || exit 0
    - name: Git Push
      run: git push

  approve_pr:
    runs-on: ubuntu-latest
    needs: compile_notes
    permissions:
      pull-requests: write
    steps:
    - name: Approve PR
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.rest.pulls.createReview({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
            event: 'APPROVE'
          })
